title: Tiberriver256
description: A blog about PowerShell mostly.
reading_time: true
words_per_minute: 200
logo: images/logo.svg
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: "https://tiberriver256.github.io"
bareUrl: "tiberriver256.github.io"
ogImageBackground: "/images/Black.jpg"

menu:
  - title: "About"
    url: "/about"
  - title: "Tags"
    url: "/tags"
  - title: "Categories"
    url: "/categories"
  - title: "RSS"
    url: "/feed.xml"

# Owner/author information
owner:
  name: Micah Rairdon
  gravatarmd5: f2cc976ebe94f2bdaa2ff21801312836
  email: "Jun(Real Email: Micah.Rairdon [GMail])k@JunkMail.com"
  # Social networking links used in footer. Update and remove as you like.
  # twitter: tiberriver256
  # facebook:
  # stackexchange:
  # instagram:
  linkedin: tiberriver256
  # flickr:
  # tumblr:
  # google plus id, include the '+', eg +AronBordin
  # google_plus:    +yourid

# Analytics and webmaster tools stuff goes here
google_analytics: G-4DS8LE3MB2
google_verify: SkYg6CIVG1p7WbqGm-KTy1l3lYOKRySzKYEt7ZI_EG8
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/New_York
future: true

markdown: kramdown
plugins:
  - jekyll-sitemap

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

cloudinary_cloud: dhff6zdnc
base64_encoded_logo_url: aHR0cHM6Ly90aWJlcnJpdmVyMjU2LmdpdGh1Yi5pby9pbWFnZXMvbG9nb19saWdodC5zdmc=

include: [".htaccess"]
exclude:
  [
    "lib",
    "config.rb",
    "Capfile",
    "config",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE",
    "log",
    "Rakefile",
    "Rakefile.rb",
    "tmp",
    "less",
    "*.sublime-project",
    "*.sublime-workspace",
    "test",
    "spec",
    "Gruntfile.js",
    "package.json",
    "node_modules",
    "vendor",
  ]
